{{- if and .Values.deployment.kong.enabled .Values.cluster.openshiftRoute.enabled }}
{{- if and .Values.cluster.enabled .Values.cluster.tls.enabled -}}
{{- $routeConfig := dict -}}
{{- $routeConfig := merge $routeConfig .Values.cluster -}}
{{- $_ := set $routeConfig "fullName" (include "kong.fullname" .) -}}
{{- $_ := set $routeConfig "namespace" (include "kong.namespace" .) -}}
{{- $_ := set $routeConfig "metaLabels" (include "kong.metaLabels" .) -}}
{{- $_ := set $routeConfig "serviceName" "cluster" -}}
{{- include "kong.route" $routeConfig }}
{{- end -}}
{{- end -}}
