{{- if .Values.postgresql.auth.existingSecret }}
{{- $pgSecretConfig := dict -}}
{{- $pgSecretConfig := merge $pgSecretConfig .Values.postgresql -}}
{{- $_ := set $pgSecretConfig "namespace" (include "kong.namespace" .) -}}
{{- $_ := set $pgSecretConfig "metaLabels" (include "kong.metaLabels" .) -}}
{{- $_ := set $pgSecretConfig "secretName" .Values.postgresql.auth.existingSecret -}}
{{- include "kong.postgresSecret" $pgSecretConfig }}
{{- end }}
